### ISSUE TITLE
rule: template-curly-spacing

### ISSUE THREAD

**Issue by flootr** [peerigon/eslint-config-peerigon#8]
Is there a specific reason, why we introduced spaces within template literals via https://github.com/peerigon/eslint-config-peerigon/commit/a3409a3613a58e002921db8cb54db0550fbfa56d? For my sense, it's a bit too much spacing around here. Though I first wanted to ask what's the reason for this @jhnns.

**Comment by jhnns** [comment]
See https://github.com/peerigon/eslint-config-peerigon/issues/5#issuecomment-261531960 for the discussion.

Are you ok with that?

**Comment by flootr** [comment]
> Are you ok with that?

Not sure. Basically, I agree with that it's simple and easy understandable to say

> After every { and before every } there is a space

but for my liking this is a bit too much. Specifically in template literals, it, dunno how to say that, expands, where it shouldn't expand.. visually.

```js
const template = `This is my ${ car }`;
// compared to
const template = `This is my ${car}`;

// or

const template = `This is my ${ color } ${ car }`.
// compared to
const template = `This is my ${color} ${car}`.
```

In my sense `${car}` is an expression which should not be _"splitted"_. Imo it removes the _"visual expression"_, that this is an _expression interpolation_.

**Comment by jhnns** [comment]
But especially in template strings I think it's good that the expression is visible on first sight.

I would like to keep the rule because this is very subjective and changing it (again) wouldn't have a big benefit. I'm ok with both, but +1 for the spacing rule because of consistency.

**Comment by flootr** [comment]
> But especially in template strings I think it's good that the expression is visible on first sight.

Correct! As I stated, for me, it removes this advantage. Especially if you're using more than one expression.

> because of consistency

Well, only if it makes sense. And it doesn't make sense for me (I'm also not agreeing with this regarding other spacing-rules, as you know) to enforce spacing here. 

> this is very subjective

It is, yes. But I'm forced to write code like this, because of a subjective opinion I am not agreeing with.

>  changing it (again) wouldn't have a big benefit

This rule was introduced without any discussion beforehand. So I think it's comprehensible to question this decision.

 Wouldn't it be an option to remove the rule, so both ways are applicable?

**Comment by jhnns** [comment]
I understand your argument that template string interpolation is different than other occurrences of curly braces.

If we change this, the spaces in props should also be removed because that is very similar to string interpolation:

```javascript
<SomeComp prop={ myProp } /> // error
<SomeComp prop={myProp} /> // ok
```

Do you agree with that?

Since it's very subjective, I think we should change that if the majority (>50%) of our current team agrees on that. Could you collect the opinions?

My opinion: Slightly against this change.

**Comment by acidicX** [comment]
> My opinion: Slightly against this change.

:+1: because this keeps the rules simple, even though I agree that it does not look particularly visually pleasing

**Comment by flootr** [comment]
> Do you agree with that?

Yup, see https://github.com/peerigon/eslint-config-peerigon/issues/5#issuecomment-233241176.

>  same here because this keeps the rules simple

Please keep in mind, that _simple_ is not necessarily tied to _having spaces_. It could also be the other way round.

Alright, then let's just use my comment here to collect the mood of our team. (Please also refer to the discussion on #5).

@peerigon/everyone please vote with

- 👍 for removing spaces as stated in https://github.com/peerigon/eslint-config-peerigon/issues/8#issuecomment-281970900
- 👎 if you want to keep spaces, like it is.
- 😄 if you don't have an opinion on that and don't wanna vote

**Comment by acidicX** [comment]
> Please keep in mind, that simple is not necessarily tied to having spaces. It could also be the other way round.

Yeah, but I definitely prefer having spaces for objects and imports. So if we want to keep it simple / consistent, having the spaces there is a bigger gain then the pain of having spaces in template strings

**Comment by matthaias** [comment]
I prefer no spaces in template strings, because one string is one let me call it element and this is not readable if there a more variables like the example with two variables. In your case @jhnns one variable belongs to one property and so this does not downgrade the readability for me. Also if one component has more properties there is a newline for every dependency. 

Hard to explain, i hope you understand me :)

**Comment by jhnns** [comment]
Still some votes missing... 😁

**Comment by matthaias** [comment]
Ok, @sbat @irenama @meaku and @Blacklist are missing. Please vote (also if you don't want thumbs up or down) so this can be closed :)

**Comment by jhnns** [comment]
I just realized that we don't have curly spaces in our `react` rules... so either we change our react rules to spaces or we switch to no spaces in template strings. Because react curly spaces and template curly spaces are conceptional related to each other (it's a form of value interpolation).

Personally, I start to accept the no-spaces rule because sometimes I find it confusing to recognize whether the extra spaces are part of the template or not. And template strings were introduced to express template strings in a concise way, so we shouldn't forbid this conciseness...

**Comment by flootr** [comment]
@jhnns any new information on this?

**Comment by jhnns** [comment]
@peerigon/everyone Has anyone a strong opinion against omitting spaces?

```js
// old
const template = `This is my ${ car }`;
// new
const template = `This is my ${car}`;
```

This aligns with our current `react` rules where we already omit spaces:

```js
<SomeComp prop={ myProp } /> // error
<SomeComp prop={myProp} /> // ok
```

**Comment by jhnns** [comment]
It's no whitespace after curly braces now. That's also consistent with the way we write arrays:

```js
{a: 1, b: 2, c: 3};
[1, 2, 3];
```
